// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkN_9EsKh_sbGM2kWfDQjTjjbKZ3YdrW4',
    appId: '1:96230233290:web:c48764281fcdfc104d9033',
    messagingSenderId: '96230233290',
    projectId: 'notifications-3ecd7',
    authDomain: 'notifications-3ecd7.firebaseapp.com',
    storageBucket: 'notifications-3ecd7.appspot.com',
    measurementId: 'G-M7KGD0NTJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu_hiCb9uuqGsN66allf-8h_vUscRTGs8',
    appId: '1:96230233290:android:bde6584b1c11d5b54d9033',
    messagingSenderId: '96230233290',
    projectId: 'notifications-3ecd7',
    storageBucket: 'notifications-3ecd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARDoQWx4uNb1h6jh7pBOZNlrZlHCwzEts',
    appId: '1:96230233290:ios:f417d72b0ae0dbaa4d9033',
    messagingSenderId: '96230233290',
    projectId: 'notifications-3ecd7',
    storageBucket: 'notifications-3ecd7.appspot.com',
    iosClientId: '96230233290-mru1qu4luj765erjhvc6dt2bejeco3u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARDoQWx4uNb1h6jh7pBOZNlrZlHCwzEts',
    appId: '1:96230233290:ios:f417d72b0ae0dbaa4d9033',
    messagingSenderId: '96230233290',
    projectId: 'notifications-3ecd7',
    storageBucket: 'notifications-3ecd7.appspot.com',
    iosClientId: '96230233290-mru1qu4luj765erjhvc6dt2bejeco3u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifications',
  );
}
